import '@saint-giong/bamboo-ui/globals.css';
import type { Metadata } from 'next';
import { Familjen_Grotesk } from 'next/font/google';

const familjenGrotesk = Familjen_Grotesk({
  subsets: ['latin'],
  variable: '--font-familjen',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${familjenGrotesk.variable} font-sans antialiased`}
        style={{ fontFamily: 'var(--font-familjen)' }}
      >
        {children}
      </body>
    </html>
  );
}
